### PR TITLE
Only duplicate headers if they already exist

### PR DESCRIPTION
**Pull request by nosmo**
Doesn't really need a feature branch but just want to be sure I'm doing this right. Was causing the following on node v0.12.0 for some reason. 

```
Proxy server listening on 127.0.0.1:9008
New headers for referer set to undefined
New headers for cookie set to undefined
debug: in Bundler.send/async.reduce, memo = url=http://nosmo.me
debug: in Bundler.send/async.reduce, memo = url=http://nosmo.me, referer=undefined, cookie=undefined
debug: in Bundler.send/async.reduce, memo = url=http://nosmo.me, referer=undefined, cookie=undefined, Origin=Bundler
_http_outgoing.js:333
    throw new Error('"name" and "value" are required for setHeader().');
          ^
Error: "name" and "value" are required for setHeader().
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at new ClientRequest (_http_client.js:101:14)
    at Object.exports.request (http.js:49:10)
    at Request.start (/root/bundler/node_modules/request/request.js:904:30)
    at Request.end (/root/bundler/node_modules/request/request.js:1635:10)
    at end (/root/bundler/node_modules/request/request.js:676:14)
    at Immediate._onImmediate (/root/bundler/node_modules/request/request.js:690:7)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

### CODE REVIEW

**Comment by redwire** [comment]
I've begun merging this in a new branch called `merging`.  Most of the merge conflicts were easy to resolve, but when I test the proxy server the way I'm doing it, I'm getting the following error, preceded by the debug info below.  I suspect that there are requests coming in for things like favicons throwing a wrench in the gears you've got spinning for the changes you made to the remapper.
If you could resolve this bug in the merging branch, I'd be happy to merge it into master as everything else looks great!

```
debug: Calling originalRequest hook with options  url=undefined, strictSSL=false, rejectUnauthorized=false, referer=http://localhost:9008/?url=https://google.com, cookie=__qca=P0-30780242-1423094710019; optimizelySegments=%7B%222025850214%22%3A%22true%22%2C%221938330135%22%3A%22true%22%2C%221506465808%22%3A%22direct%22%2C%221717910483%22%3A%22none%22%2C%221505515733%22%3A%22false%22%2C%221503675771%22%3A%22ff%22%2C%221893480508%22%3A%22true%22%2C%221933410265%22%3A%22true%22%7D; optimizelyEndUserId=oeu1423094710572r0.016382097743280033; optimizelyBuckets=%7B%222469530535%22%3A%222438501470%22%7D; _ga=GA1.1.14051304.1423094711; 4chan_disclaimer=1; __utma=111872281.14051304.1423094711.1423169020.1423169020.1; __utmz=111872281.1423169020.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __gads=ID=5ac9a9b65221e03d:T=1423169019:S=ALNI_MbGR3dbI1FAb8bsBhFmcsmSJtsYWQ; _em_vt=deae93581822b82470dcda94db0b54d3d5fc9b8ba9-3949341054d3d5fc; _cb_ls=1; _chartbeat2=DndyQyDOvgSUDDcTNP.1423169054892.1423169054892.1, Origin=Bundler, followRedirect=true, followAllRedirects=false, maxRedirects=10

url.js:107
    throw new TypeError("Parameter 'url' must be a string, not " + typeof url)
          ^
TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:107:11)
    at Object.urlParse [as parse] (url.js:101:5)
    at /Users/redwire/Developer/Sources/Projects/bundler/applications/proxyserver.js:56:21
    at /Users/redwire/Developer/Sources/Projects/bundler/src/bundler.js:68:5
    at /Users/redwire/Developer/Sources/Projects/bundler/node_modules/async/lib/async.js:272:13
    at iterate (/Users/redwire/Developer/Sources/Projects/bundler/node_modules/async/lib/async.js:149:13)
    at /Users/redwire/Developer/Sources/Projects/bundler/node_modules/async/lib/async.js:160:25
    at /Users/redwire/Developer/Sources/Projects/bundler/node_modules/async/lib/async.js:274:17
    at /Users/redwire/Developer/Sources/Projects/bundler/src/requests.js:50:7
    at /Users/redwire/Developer/Sources/Projects/bundler/src/bundler.js:68:5
```

**Comment by nosmo** [comment]
Could you give me some details on how you produced this bug? It looks very familiar but I can't seem to trigger it. How are you configuring your browser to use the proxy?

**Comment by redwire** [comment]
Strangely, I no longer have the problem I mentioned when I test in either Firefox or Chrome.

For your reference, however: I hadn't been configuring my browser to use the proxyserver as a proxy. I would simply enter URLs as `localhost:9008/?url=[the url to test]`

**Comment by nosmo** [comment]
Huh... I just managed to reproduce this after all :( 

I'd been testing with curl again, which is silly as it seems too simple and so it ignores these edge cases. Get the crash consistently with Firefox browsing to http://127.0.0.1:9008/?url=https://google.com. 

I'll look into a fix for this.

**Pull request merged**
